### ISSUE TITLE
'Buffer' pull mode for ICARUS CRT

### ISSUE THREAD

**Issue by wesketchum** [SBNSoftware/sbndaq#2]
Should enable and test a 'buffer' pull mode for the ICARUS CRT FragmentGenerators, and then include them by default in the DAQ runs.

@aaduszki, @chilge, and @tboone0042. Can you make sure the FragmentGenerator in sbndaq-artdaq is reasonable up to date with how things are being tested/run now standalone. 

And can you point me to your analysis code for looking at the data from artdaqDriver? I will suggest a few line changes for dealing with the new ContainerFragment format (unless you have already handled those...)

**Comment by aaduszki** [comment]
@wesketchum This is the analysis code in a version that should support both pull mode and push mode data formats:
https://cdcvs.fnal.gov/redmine/projects/sbndaq/repository/artdaq/entry/sbndaq-artdaq/ArtModules/Common/BernCRTZMQAna_module.cc?utf8=%E2%9C%93&rev=feature%2Faaduszki_integrate_febdrv
Please see the if/else blocks at lines 166–181. Does it look correct to you?

There are of course other codes that @chilge and @tboone0042 develop for reconstruction and OM, but I think we use this as a model code.

**Comment by wesketchum** [comment]
This is done and in place and tested and running at SBN-FD. closing.
